name: Interrupt
favicon: null
layout_spectrum: 0.775129497051239
typography_spectrum: 0.841448292369023
title: Interrupt Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2825'
    - '#d38837'
    - '#848a7c'
    - '#f8b356'
  brandStrength: 1
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
